name: 'Deploy infrasructure'
on:
  push:
    paths:
      - .github/workflows/setup-infrastructure.yml
      - packages/infra/**
jobs:
  deploy:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Install dependencies
        run: npm ci
      - run: npx aws-cdk deploy dns --require-approval never
        working-directory: ./packages/infra
      - run: npx aws-cdk deploy server --require-approval never
        working-directory: ./packages/infra
      - run: gh workflow run deploy-to-s3.yml
        env:
          GH_TOKEN: ${{ github.token }}