name: 'Test'
on:
  workflow_dispatch:
permissions: write-all
jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - run: gh variable set AWS_TEST --body "1"
        env:
          GH_TOKEN: ${{ github.token }}